### ISSUE TITLE
CI/CD: fix some workflows running slowly

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#1055]
- occlum SGX2：centos 8.2, ubuntu 18.04, and alinux 2 
https://github.com/alibaba/inclavare-containers/pull/1052/checks?check_run_id=2644684172

- crictl SGX2:

![image](https://user-images.githubusercontent.com/6824093/119215753-3ea10200-bb02-11eb-95e0-87b91556fb1d.png)

![image](https://user-images.githubusercontent.com/6824093/119215745-3943b780-bb02-11eb-825a-cccd4134796f.png)

**Comment by haosanzi** [comment]
The reason is that the new cicd machine does not install `enable_rdfsbase kernel module`.
The problem has been fixed. The test result is showed in [link](https://github.com/haosanzi/inclavare-containers/runs/2645803928?check_suite_focus=true)
