### ISSUE TITLE
docs/k8s: update `Install Linux SGX software stack` 

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#1070]
@jiazhiguang You need to update this section to support SGX1 and SGX 2 drivers and update the sgxsdk version to 2.13.

![image](https://user-images.githubusercontent.com/6824093/119321879-aea0bb00-bcaf-11eb-90e4-8400857e72ec.png)

**Comment by jiazhang0** [comment]
In addition, it is required to emphasize that the host version of sgx sdk where the signing tool is running must be same with the one where Occlum SDK image uses.
