### ISSUE TITLE
shelter: depends on enclave-tls in build dir instead of /opt

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#1071]
![image](https://user-images.githubusercontent.com/26923638/119363978-0277c800-bce1-11eb-83ae-94bda7536a57.png)

**Comment by zhiminghufighting** [comment]
Confirmed with Yanrong offline, this issue request shelter to remove enclave-tls dependence with opt in Makefile. 
Is my understanding correct?
If yes,  we can remove th edepends partly in Make file by remove "install" and by changing CGO LDFLAGS library path from /opt/enclave-tls/lib to ../../enclave-tls/build/lib.
Actually shelter compiling depends on /opt/enclave-tls/include/api.h,  shelter can't remove /opt directory totally in compiling stage.
Based on that condition, do we need to remove the dependence?
@jiazhang0

**Comment by jiazhang0** [comment]
The build system of enclave-tls will be changed to cmake. So this issue will be considered after the mitigation to cmake.

**Comment by zhiminghufighting** [comment]
OK， let's push this issue to the next milestone.
