### ISSUE TITLE
Failed to run WAMR as enclave runtime

### ISSUE THREAD

**Issue by lifeng68** [alibaba/inclavare-containers#1099]
Hi, i want to test rune with WAMR as the enclave runtime. But i got the error as below.

```
~/rune_workdir/rune-container » sudo docker run -it --runtime=rune  \                                                                                                  
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=debug \                 
  wamr-sgx-app
lifeng add:/
Failed to create enclave from /enclave.signed.so, error code: 8207
Fail to initialize enclave.
Call ecall_handle_command() failed.
Failed to init runtime
pal create process() failed with -1
```
I tried to debug the issue, found that the work dir is not correct. I place the enclave.signed.so under `run/rune`, but the rune cannot find it, becase the working dir is `/`. Did i miss something?

```
static int
enclave_init(sgx_enclave_id_t *p_eid)

{
    char token_path[MAX_PATH] = { '\0' };
    char enclave_path[MAX_PATH] = { '\0' };
    const char *home_dir;
    sgx_launch_token_t token = { 0 };
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    int updated = 0;
    size_t write_num, enc_file_len;
    FILE *fp;

    enc_file_len = strlen(ENCLAVE_FILENAME);
    if (!get_exe_path(enclave_path, sizeof(enclave_path) - enc_file_len)) {
        printf("Failed to get exec path\n");
        return -1;
    }
    printf("lifeng add:%s\n", enclave_path);
```

**Comment by hustliyilin** [comment]
> wamr-sgx-app

Thanks for your question. Could you provide the `dockerfile` of your `wamr-sgx-app` docker image?

**Comment by jiazhang0** [comment]
@lifeng68 enclave.signed.so file should be placed under CWD (workdir) of docker image. Please try it.

**Comment by lifeng68** [comment]
> @lifeng68 enclave.signed.so file should be placed under WORKDIR of docker image. The README.md mentions the location of WORKDIR should be `/run/rune/` inside container:
> 
> ```shell
> cat >Dockerfile <<EOF
> FROM centos:8.1.1911
> 
> RUN mkdir -p /run/rune
> WORKDIR /run/rune
> 
> COPY enclave.signed.so .
> COPY test.aot app 
> #COPY ${wasm_app.aot} .
> ENTRYPOINT ["/run/rune/app"]
> EOF
> ```

@jiazhang0  I used the Dockerfile same as yours, inspect the image as below, the WORKDIR is `/run/rune/`:

```
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "sha256:08a0d4a95cefb408adf81c70300dd86a54ebc7c81cfd52c41f327ee2a8de8599",
            "Volumes": null,
            "WorkingDir": "/run/rune",
            "Entrypoint": [
                "/run/rune/app"
            ],
            "OnBuild": null,
            "Labels": null
        },
```

**Comment by jiazhang0** [comment]
@lifeng68 Use --workdir with docker command?

**Comment by lifeng68** [comment]
> @lifeng68 Use `--workdir /` with docker command?

No, I did not set the workdir, i add the debug info print the cwd in pal.so, and i found that the WORKDIR is correct, but still cannot   find the enclave.signed.so

```
static int
enclave_init(sgx_enclave_id_t *p_eid)

{
    char token_path[MAX_PATH] = { '\0' };
    char enclave_path[MAX_PATH] = { '\0' };
    char pwd_path[MAX_PATH] = { '\0' };
    const char *home_dir;
    sgx_launch_token_t token = { 0 };
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    int updated = 0;
    size_t write_num, enc_file_len;
    FILE *fp;

    printf("lifeng add [cwd]:%s\n", getcwd(pwd_path, MAX_PATH));
```

When i run the container, the cwd print is /run/rune

```
~/rune_workdir/rune-container » sudo docker run -it --runtime=rune  \                                                                                                  130 ↵
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=debug \
  wamr-sgx-app
lifeng add [cwd]:/run/rune
lifeng add:/
Failed to create enclave from /enclave.signed.so, error code: 8207
Fail to initialize enclave.
Call ecall_handle_command() failed.
Failed to init runtime
pal create process() failed with -1
```

**Comment by jiazhang0** [comment]
> > @lifeng68 Use `--workdir /` with docker command?
> 
> No, I did not set the workdir, i add the debug info print the cwd in pal.so, and i found that the WORKDIR is correct, but still cannot find the enclave.signed.so
> 
> ```
> static int
> enclave_init(sgx_enclave_id_t *p_eid)
> 
> {
>     char token_path[MAX_PATH] = { '\0' };
>     char enclave_path[MAX_PATH] = { '\0' };
>     char pwd_path[MAX_PATH] = { '\0' };
>     const char *home_dir;
>     sgx_launch_token_t token = { 0 };
>     sgx_status_t ret = SGX_ERROR_UNEXPECTED;
>     int updated = 0;
>     size_t write_num, enc_file_len;
>     FILE *fp;
> 
>     printf("lifeng add [cwd]:%s\n", getcwd(pwd_path, MAX_PATH));
> ```
> 
> When i run the container, the cwd print is /run/rune
> 
> ```
> ~/rune_workdir/rune-container » sudo docker run -it --runtime=rune  \                                                                                                  130 ↵
>   -e ENCLAVE_TYPE=intelSgx \
>   -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
>   -e ENCLAVE_RUNTIME_ARGS=debug \
>   wamr-sgx-app
> lifeng add [cwd]:/run/rune
> lifeng add:/
> Failed to create enclave from /enclave.signed.so, error code: 8207
> Fail to initialize enclave.
> Call ecall_handle_command() failed.
> Failed to init runtime
> pal create process() failed with -1
> ```

How about if you set `--workdir /` with docker command?

**Comment by lifeng68** [comment]
> --workdir /

Same failed.

```
~/rune_workdir/rune-container » sudo docker run -it --runtime=rune --workdir=/ \                                                                                         1 ↵
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=debug \
  wamr-sgx-app
lifeng add [cwd]:/
lifeng add:/
Failed to create enclave from /enclave.signed.so, error code: 8207
Fail to initialize enclave.
Call ecall_handle_command() failed.
Failed to init runtime
pal create process() failed with -1
```

**Comment by haosanzi** [comment]
@lifeng68 We have provide WebAssembly Micro Runtime (WAMR) application image. Could you please run the following command to see what happens?
```shell
docker run -it --rm --runtime=rune   -e ENCLAVE_TYPE=intelSgx   \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so   \
  -e ENCLAVE_RUNTIME_ARGS=debug \
  inclavarecontainers/enclave-wamr
```
The expected result is that:
![image](https://user-images.githubusercontent.com/26923638/122180947-79a51400-cebb-11eb-8f6f-52f2a76acfdc.png)

**Comment by lifeng68** [comment]
> ```shell
> docker run -it --rm --runtime=rune   -e ENCLAVE_TYPE=intelSgx   \
>   -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so   \
>   -e ENCLAVE_RUNTIME_ARGS=debug \
>   inclavarecontainers/enclave-wamr
> ```

![image](https://user-images.githubusercontent.com/26912745/122181933-6181c480-cebc-11eb-90a6-67877280ea4d.png)

**Comment by lifeng68** [comment]
I build the follow the [guide]( https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/linux_sgx.md#build-wamr-vmcore-iwasm-for-linux-sgx), do i need to `make SGX_MODE=HW`?

**Comment by haosanzi** [comment]
To build the enclave running on a hardware-based SGX platform, execute make SGX_MODE=HW (default is SIM).
Please use `make SGX_MODE=HW` command to build enclave sample.

**Comment by lifeng68** [comment]
Version:
* wasm-micro-runtime 
[main branch](https://github.com/bytecodealliance/wasm-micro-runtime/commit/1a4aa5ac2f659439a344c0ec7163b157c0e190ce)

* rune [main branch](https://github.com/alibaba/inclavare-containers/commit/3e9ee348ee47c575d295eda61affc252075f8939)

**Comment by lifeng68** [comment]
> To build the enclave running on a hardware-based SGX platform, execute make SGX_MODE=HW (default is SIM).
> Please use `make SGX_MODE=HW` command to build enclave sample.

@haosanzi When i make with SGX_MODE=HW, need the signing key to sign the so, but i donot have the key. Is SIM mode unable to run in WAMR? The example image inclavarecontainers/enclave-wamr is make in HW mode? Thanks.

```
CP libvmlib.a  <=  ../build/libvmlib.a
LINK =>  enclave.so
The project has been built in release hardware mode.
Please sign the enclave.so first with your signing key before you run the iwasm to launch and access the enclave.
To sign the enclave use the command:
   /opt/intel/sgxsdk/bin/x64/sgx_sign sign -key <your key> -enclave enclave.so -out <enclave.signed.so> -config Enclave/Enclave.config.xml
You can also sign the enclave using an external signing tool. See User's Guide for more details.
To build the project in simulation mode set SGX_MODE=SIM. To build the project in prerelease mode set SGX_PRERELEASE=1 and SGX_MODE=HW.
```

**Comment by haosanzi** [comment]
@lifeng68 The example image inclavarecontainers/enclave-wamr is made in HW mode. Please follow this command to build 
libwamr-pal.so.
```shell
git clone https://github.com/bytecodealliance/wasm-micro-runtime
cd wasm-micro-runtime/product-mini/platforms/linux-sgx/        
mkdir build; 
cd build; cmake ..; make ;        
cd ../enclave-sample ; make SGX_MODE=HW;       
g++ -shared -fPIC -o libwamr-pal.so App/*.o libvmlib_untrusted.a -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lpthread -lssl -lcrypto;        cp ./libwamr-pal.so /usr/lib/libwamr-pal.so;
```

**Comment by lifeng68** [comment]
> ```shell
> g++ -shared -fPIC -o libwamr-pal.so App/*.o libvmlib_untrusted.a -L/opt/intel/sgxsdk/lib64 -lsgx_urts -lpthread -lssl -lcrypto
> ```

It works! The problem may be becase i used the SIM mode to build the libwamr-pal.so. 
Can i run the SIM mode in WAMR? I don't have the signing keys, but i want to hack the rune and inclave container.Thanks.
![image](https://user-images.githubusercontent.com/26912745/122190043-081d9380-cec4-11eb-97fa-49a15310508a.png)

**Comment by haosanzi** [comment]
@lifeng68 You can generate a key instead of using key provided by warm to sign your enclave.
Wamr supports sim mode, but rune does not support sim mode. Welcome to contribute!!

**Comment by lifeng68** [comment]
> @lifeng68 You can generate a key instead of using key provided by warm to sign your enclave.
> Wamr supports sim mode, but rune does not support sim mode. Welcome to contribute!!

Thanks, i tested with the rune successfully, so close the issue.

* sign the enclave.signed.so
`# /opt/intel/sgxsdk/bin/x64/sgx_sign sign -key ./Enclave/Enclave_private.pem -enclave enclave.so -out enclave.signed.so -config Enclave/Enclave.config.xml`
* copy the enclave.signed.so to my rootfs
 ` sudo cp /home/lifeng/WAMR/wasm-micro-runtime/product-mini/platforms/linux-sgx/enclave-sample/enclave.signed.so ./rootfs/var/run/rune/`

* run with rune

```
~/rune_workdir/rune-container » sudo rune run lifeng2
INFO[0000] Initializing enclave runtime                 
Warning: Failed to create/open the launch token file "/root/enclave.token".
Hello world!
buf ptr: 0x11510
buf: 1234
```
