### ISSUE TITLE
Copyright format change request

### ISSUE THREAD

**Issue by zhiminghufighting** [alibaba/inclavare-containers#1102]
Please change Copyright format of all code files into below format:
/* Copyright (c) 20xx-20yy Alibaba Cloud 
* Copyright (c) 2021 Intel Corporation
* SPDX-License-Identifier: Apache-2.0
*/

**Comment by jiazhang0** [comment]
Will use the following format:

```
/* Copyright (c) 2021 Intel Corporation
 * Copyright (c) 2020-2021 Alibaba Cloud
 *
 * SPDX-License-Identifier: Apache-2.0
 */
```

**Comment by jiazhang0** [comment]
Resolved by https://github.com/alibaba/inclavare-containers/commit/6afd527bf0dbcf56d05724a7dcb27ef8a377c47a
