### ISSUE TITLE
CI/CD failure: occlum test unstoppable

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1130]
https://github.com/alibaba/inclavare-containers/pull/1127/checks?check_run_id=2863345480

**Comment by jiazhang0** [comment]
Re-run doesn't resolve the problem. Looks like something goes wrong.

**Comment by haosanzi** [comment]
install enable_rdfsbase module can solve this problem.

**Comment by jiazhang0** [comment]
Manual installation of enable_rdfsbase is not a complete solution. It is just a workaround. I think there is a way of solution. @jiazhiguang @haosanzi
