### ISSUE TITLE
skeleton: build failure

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1132]
https://github.com/alibaba/inclavare-containers/pull/1127/checks?check_run_id=2863345498

**Comment by haosanzi** [comment]
It is difficult to reproduce the error. This problem occurs with a low probability. At present, rerun jobs to workaround this problem.

**Comment by jiazhang0** [comment]
Happen again：https://github.com/alibaba/inclavare-containers/pull/1162/checks?check_run_id=2884366348

I think you just don't get a way to reproduce it. @haosanzi

**Comment by hustliyilin** [comment]
I think if it occurs, we should login the docker container to check the protoc version and protoc-c version. The error about aesm.pb-c.h not found is  that aesm.pb-c.h isn't generated by protoc and protoc-c.
