### ISSUE TITLE
CI/CD: disable the enclave-tls openssl testing on alinux2

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1139]
Refer to https://github.com/alibaba/inclavare-containers/issues/1138

https://github.com/alibaba/inclavare-containers/pull/1135/checks?check_run_id=2866922076

**Comment by jiazhang0** [comment]
This is a workaround. And https://github.com/alibaba/inclavare-containers/issues/1138 will resolve this issue from root.

**Comment by haosanzi** [comment]
Typing the following command to install openssl1.1 in alinux2 images:
```shell
yum install openssl11  openssl11-devel
openssl11 version
OpenSSL 1.1.1g FIPS  21 Apr 2020
```
