### ISSUE TITLE
sgx 1 sgx-tools gen-qe-target-info doesn't work

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#1142]
https://github.com/alibaba/inclavare-containers/pull/1135/checks?check_run_id=2874689823

In SGX2, it seems no problem.

![image](https://user-images.githubusercontent.com/6824093/122762769-3dfdb600-d2d0-11eb-854c-2d83746d349a.png)

However In SGX1 , it doesn't work.

![image](https://user-images.githubusercontent.com/6824093/122762818-4c4bd200-d2d0-11eb-9fa2-5c9bb5cc4c47.png)

It could be found that the aesmd service has a problem like this

![image](https://user-images.githubusercontent.com/6824093/122762991-71d8db80-d2d0-11eb-88f2-f98905790d57.png)

**Comment by jiazhang0** [comment]
@haosanzi Please install libsgx-aesm-epid-plugin for dev-alinux2, and install libsgx-aesm-launch-plugin and libsgx-aesm-epid-plugin for dev-ubuntu and dev-cantos.

**Comment by hustliyilin** [comment]
In another SGX1 centos 8 machine，it seems work

![image](https://user-images.githubusercontent.com/6824093/122868212-3f28f480-d35d-11eb-88db-2388009a3d51.png)

**Comment by hustliyilin** [comment]
I guess this is not the sgx-tools problem but the environment problem. @haosanzi could you fix the environment problem ?

**Comment by jiazhang0** [comment]
https://github.com/alibaba/inclavare-containers/pull/1146/checks?check_run_id=2881861442
https://github.com/alibaba/inclavare-containers/pull/1146/checks?check_run_id=2881861442

Another two cases.

**Comment by jiazhang0** [comment]
This problem is resolved after upgrade from 2.13 to 2.13.3.
