### ISSUE TITLE
shelter: cannot stat '/root/inclavare-containers-/enclave-tls/samples/sgx-stub-enclave/sgx_stub_enclave.signed.so'

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1148]
https://github.com/alibaba/inclavare-containers/pull/1146/checks?check_run_id=2881475794

In "Build shelter":

```
cp: cannot stat '/root/inclavare-containers-/enclave-tls/samples/sgx-stub-enclave/sgx_stub_enclave.signed.so': No such file or directory
```

**Comment by jiazhang0** [comment]
Refer to L40 in https://github.com/haosanzi/inclavare-containers/commit/83b7850e56189167a7659d8abcb4904e30a44425 for the reference to the fix. @zhiminghufighting

**Comment by zhiminghufighting** [comment]
Yes, many cicd ymls are needed to adjusted at the same time.
