### ISSUE TITLE
CI/CD: No such image: inclavarecontainers/dev:0.6.2-centos8.2

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1209]
https://github.com/alibaba/inclavare-containers/pull/1208/checks?check_run_id=2948682214

**Comment by jiazhang0** [comment]
https://github.com/alibaba/inclavare-containers/pull/1208/checks?check_run_id=2948685497
https://github.com/alibaba/inclavare-containers/pull/1208/checks?check_run_id=2948679276

**Comment by haosanzi** [comment]
`inclavarecontainers/dev:0.6.2-{{os}}` has been upsdated.
