### ISSUE TITLE
rats-tls: select the enclave verifier 'nulltls'

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#1317]
```
./rats-tls-server -a sgx_ecdsa
./rats-tls-client -v sgx_ecdsa
```

**Comment by jiazhang0** [comment]
Need to attempt to reproduce this issue in rats-tls.

**Comment by zhiminghufighting** [comment]
Reproduced the issue:
[zhimingh@localhost rats-tls-server]$ sudo ./rats-tls-server -a sgx_ecdsa
    - Welcome to Rats-TLS sample server program for Intel SGX
[INFO] load_enclave()@L47: Success to load enclave with enclave id 2
[INFO] rtls_crypto_wrapper_select()@L67: the crypto wrapper 'nullcrypto' selected
[INFO] rtls_attester_select()@L74: the enclave attester 'sgx_ecdsa' selected
[INFO] rtls_verifier_select()@L69: the enclave verifier 'nullverifier' selected
[INFO] rtls_tls_wrapper_select()@L68: the tls wrapper 'nulltls' selected

**Comment by zhiminghufighting** [comment]
still can be reproduced based on commit id: c262921b4659bdbe4dc4e8ceaf54789afe8e0937(rats-tls: rename the names of attester and verifier instance for tdx …)

[root@localhost rats-tls-server]# ./rats-tls-server -a sgx_ecdsa
    - Welcome to Rats-TLS sample server program for Intel SGX
[INFO] load_enclave()@L47: Success to load enclave with enclave id 2
[INFO] rtls_crypto_wrapper_select()@L67: the crypto wrapper 'nullcrypto' selected
[INFO] rtls_attester_select()@L74: the enclave attester 'sgx_ecdsa' selected
[INFO] rtls_verifier_select()@L73: the enclave verifier 'nullverifier' selected
[INFO] rtls_tls_wrapper_select()@L68: the tls wrapper 'nulltls' selected

**Comment by jiazhang0** [comment]
Essentially, this issue addresses this error:
```
[ERROR] etls_verifier_select()@L62: failed to select the enclave verifier 'nulltls'
```

nulltls should not be enumerated by etls_verifier_select(). Looks like this issue has been resolved. Closed.
