### ISSUE TITLE
rats-tls: static link libenclave_tls_u.a bug

### ISSUE THREAD

**Issue by voidC1326** [alibaba/inclavare-containers#1353]
After static linking libenclave_tls_u.a，miss following system calls:
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_exit':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:20: undefined reference to `exit'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_opendir':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:44: undefined reference to `opendir'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_readdir':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:68: undefined reference to `readdir'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_closedir':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:102: undefined reference to `closedir'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_read':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:107: undefined reference to `read'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_write':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:112: undefined reference to `write'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_getenv':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:119: undefined reference to `getenv'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `current_time':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:130: undefined reference to `gettimeofday'
/usr/local/bin/ld: ./lib/libenclave.a(etls_syscalls_ocall.c.o): in function `ocall_low_res_time':
/root/inclavare-containers/rats-tls/src/sgx/untrust/etls_syscalls_ocall.c:152: undefined reference to `gettimeofday'

**Comment by YangLiang3** [comment]
should be lack of libc library in rust
