### ISSUE TITLE
rats-tls: support packaging for ubuntu 20.04

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1492]
Kata CC will integrate AA and verdictd used in ubuntu 20.04.

**Comment by haosanzi** [comment]
The repo url for sgx 2.14 dcap based on cento7.9 is https://mirrors.openanolis.cn/inclavare-containers/centos7.9/sgx-2.14/

**Comment by haosanzi** [comment]
The package has been provided and is being tested.

**Comment by haosanzi** [comment]
According to the test result provided by @liangzhou121, the function of [rats-tls deb](https://mirrors.openanolis.cn/inclavare-containers/ubuntu20.04/rats-tls_0.6.4-1_amd64.deb) works fine.
