### ISSUE TITLE
rats-tls: SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#1534]
Steps to reproduce

1. start rats-tls-server in host mode
```
# Launch container 1:
cd rats-tls
cmake -DBUILD_SAMPLES=on -H. -Bbuild
make -C build install
./rats-tls-server -a nullattester --verifier nullverifier -t openssl -c openssl -l debug
```

2. start rats-tls-client in sgx mode
```
# Launch container 1:
cd rats-tls
cmake -DRATS_TLS_BUILD_MODE="sgx" -DBUILD_SAMPLES=on -H. -Bbuild
make -C build install
 ./rats-tls-client -a nullattester -v nullverifier -t openssl -c openssl -l debug
```

Then the following error occurs:
```
# server 
Fri Dec 24 03:36:27 UTC 2021: [DEBUG] openssl_internal_negotiate()@L80: failed to negotiate 0xffffffff
Fri Dec 24 03:36:27 UTC 2021: [DEBUG] print_openssl_err()@L44: Error 14094418: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
[ERROR] Failed to negotiate 0x907fffff

# client
[DEBUG] openssl_tls_negotiate()@L110: ctx 0x7f42d83d6f60, fd 3
[ERROR] calc_pubkey_hash()@L103: Unable to get rsa key
[DEBUG] openssl_internal_negotiate()@L82: failed to connect 0xffffffff
[DEBUG] print_openssl_err()@L44: Error 607907f: error:0607907F:digital envelope routines:EVP_PKEY_get0_RSA:expecting an rsa key
[DEBUG] print_openssl_err()@L44: Error 1416f086: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[ERROR] ecall_rtls_client_startup()@L197: Failed to negotiate 0x907fffff
[DEBUG] rats_tls_cleanup()@L20: handle 0x7f42d83d6d20
[DEBUG] openssl_tls_cleanup()@L13: ctx 0x7f42d83d6f60
[DEBUG] nullattester_cleanup()@L12: called
```

**Comment by zhiminghufighting** [comment]
After set the default algo in sgx server and client mode, it works as below:

Client:
======
[root@FHF01 rats-tls-client]# ./rats-tls-client -a nullattester -v nullverifier -t openssl -c openssl -l debug
    - Welcome to RATS-TLS sample client program for Intel SGX
[INFO] load_enclave()@L49: Success to load enclave with enclave id 2
[DEBUG] rtls_crypto_wrapper_select()@L27: selecting the crypto wrapper 'openssl' ...
[DEBUG] openssl_init()@L16: ctx 0x7f62483c8e20
[INFO] rtls_crypto_wrapper_select()@L67: the crypto wrapper 'openssl' selected
[DEBUG] rtls_attester_select()@L33: selecting the enclave attester 'nullattester' cert algo '0x1'...
[DEBUG] init_enclave_attester()@L18: called enclave core ctx: 0x483c8d20 enclave attester ctx: 0x483c8e80 algo: 0x1
[DEBUG] nullattester_init()@L14: ctx 0x7f62483c8e80, algo 1
[INFO] rtls_attester_select()@L75: the enclave attester 'nullattester' selected
[DEBUG] rtls_verifier_select()@L32: selecting the enclave verifier 'nullverifier' ...
[DEBUG] init_enclave_verifier()@L17: init enclave verifier rtls_core_context: 0x483c8d20
[DEBUG] nullverifier_init()@L14: ctx 0x7f62483c8ef0, algo 1
[INFO] rtls_verifier_select()@L73: the enclave verifier 'nullverifier' selected
[DEBUG] rtls_tls_wrapper_select()@L28: selecting the tls wrapper 'openssl' ...
[DEBUG] openssl_tls_init()@L14: ctx 0x7f62483c8f60
[INFO] rtls_tls_wrapper_select()@L68: the tls wrapper 'openssl' selected
[DEBUG] rats_tls_init()@L106: the handle 0x7f62483c8d20 returned
[DEBUG] rats_tls_set_verification_callback()@L12: set user verification callback handle: 0x7f624bdbd988, cb 0x0
[DEBUG] rats_tls_negotiate()@L15: handle 0x7f62483c8d20, fd 3
[DEBUG] openssl_tls_negotiate()@L110: ctx 0x7f62483c8f60, fd 3
[DEBUG] sha256_ecc_pubkey()@L61: the sha256 of public key [91] 45e50e7077cd7dc7...4111ff88
[DEBUG] find_oid()@L125: there are no extensions in X509 cert
[DEBUG] find_oid()@L125: there are no extensions in X509 cert
[DEBUG] find_oid()@L125: there are no extensions in X509 cert
[WARN] openssl_extract_x509_extensions()@L275: Unhandled evidence type nullverifier
[DEBUG] tls_wrapper_verify_certificate_extension()@L20: tls_wrapper_verify_certificate_extension() called with evidence type: 'nullverifier'
[DEBUG] nullverifier_verify_evidence()@L14: ctx 0x7f62483c8ef0, evidence 0x7f624bdbb520, hash 0x7f624bdbb420
[DEBUG] sha256_ecc_pubkey()@L61: the sha256 of public key [91] 45e50e7077cd7dc7...4111ff88
[DEBUG] find_oid()@L125: there are no extensions in X509 cert
[DEBUG] find_oid()@L125: there are no extensions in X509 cert
[DEBUG] find_oid()@L125: there are no extensions in X509 cert
[WARN] openssl_extract_x509_extensions()@L275: Unhandled evidence type nullverifier
[DEBUG] tls_wrapper_verify_certificate_extension()@L20: tls_wrapper_verify_certificate_extension() called with evidence type: 'nullverifier'
[DEBUG] nullverifier_verify_evidence()@L14: ctx 0x7f62483c8ef0, evidence 0x7f624bdbb4d0, hash 0x7f624bdbb3d0
[DEBUG] openssl_internal_negotiate()@L94: success to connect
[DEBUG] rats_tls_transmit()@L16: handle 0x7f62483c8d20, buf 0x7f62482ca2e0, buf_size 0x7f624bdbd990 (Zd-byte)
[DEBUG] openssl_tls_transmit()@L13: ctx 0x7f62483c8f60, buf 0x7f62482ca2e0, buf_size 0x7f624bdbd990
[DEBUG] rats_tls_receive()@L16: handle 0x7f62483c8d20, buf 0x7f624bdbda70, buf_size 0x7f624bdbd990 (Zd-byte)
[DEBUG] openssl_tls_receive()@L13: ctx 0x7f62483c8f60, buf 0x7f624bdbda70, buf_size 0x7f624bdbd990
[INFO] ecall_rtls_client_startup()@L242: Server: Hello and welcome to RATS-TLS!

[DEBUG] rats_tls_cleanup()@L20: handle 0x7f62483c8d20
[DEBUG] openssl_tls_cleanup()@L13: ctx 0x7f62483c8f60
[DEBUG] nullattester_cleanup()@L12: called
[DEBUG] nullverifier_cleanup()@L12: called enclave verifier ctx: 0x483c8ef0


Server:
======
[root@FHF01 rats-tls-server]# ./rats-tls-server -a nullattester --verifier nullverifier -t openssl -c openssl -l debug
    - Welcome to RATS-TLS sample server program
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rats_tls_init()@L22: conf 0x7ffd375917b0, handle 0x7ffd37591788
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rtls_crypto_wrapper_select()@L27: selecting the crypto wrapper 'openssl' ...
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_init()@L16: ctx 0x1cd1cd0
[INFO] the crypto wrapper 'openssl' selected
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rtls_attester_select()@L33: selecting the enclave attester 'nullattester' cert algo '0x1'...
Fri Dec 31 04:34:41 CST 2021: [DEBUG] init_enclave_attester()@L18: called enclave core ctx: 0x1c9e910 enclave attester ctx: 0x1c9e6b0 algo: 0x1
Fri Dec 31 04:34:41 CST 2021: [DEBUG] nullattester_init()@L14: ctx 0x1c9e6b0, algo 1
[INFO] the enclave attester 'nullattester' selected
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rtls_verifier_select()@L32: selecting the enclave verifier 'nullverifier' ...
Fri Dec 31 04:34:41 CST 2021: [DEBUG] init_enclave_verifier()@L17: init enclave verifier rtls_core_context: 0x1c9e910
Fri Dec 31 04:34:41 CST 2021: [DEBUG] nullverifier_init()@L14: ctx 0x1c9ea00, algo 1
[INFO] the enclave verifier 'nullverifier' selected
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rtls_tls_wrapper_select()@L28: selecting the tls wrapper 'openssl' ...
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_tls_init()@L14: ctx 0x1c9ea70
[INFO] the tls wrapper 'openssl' selected
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rtls_core_generate_certificate()@L15: ctx 0x1c9e910
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_privkey()@L22: ctx 0x1cd1cd0, algo 1, privkey_buf 0x7ffd37590c30, privkey_len 0x7ffd37590c2c
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_privkey()@L30: 2048-byte private key buffer requested ...
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_privkey()@L90: ECC-256 private key (121-byte) in DER format generated
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_pubkey_hash()@L18: ctx 0x1cd1cd0, algo 1, hash 0x7ffd3758cb10
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_pubkey_hash()@L37: the sha256 of public key [91] 45e50e7077cd7dc7...4111ff88
Fri Dec 31 04:34:41 CST 2021: [DEBUG] nullattester_collect_evidence()@L15: ctx 0x1c9e6b0, evidence 0x7ffd3758ebec, algo 1, hash 0x7ffd3758cb10
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_cert()@L75: ctx 0x1cd1cd0, cert_info 0x7ffd3758cbd0
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_cert()@L128: evidence type '' requested
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_gen_cert()@L176: self-signing certificate generated
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_tls_use_privkey()@L14: ctx 0x1c9ea70, privkey_buf 0x7ffd37590c30, privkey_len 121
Fri Dec 31 04:34:41 CST 2021: [DEBUG] openssl_tls_use_cert()@L13: ctx 0x1c9ea70, cert_info 0x7ffd3758cbd0
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rats_tls_init()@L106: the handle 0x1c9e910 returned
Fri Dec 31 04:34:41 CST 2021: [DEBUG] rats_tls_set_verification_callback()@L12: set user verification callback handle: 0x7ffd37591788, cb (nil)
[INFO] Waiting for a connection ...
Fri Dec 31 04:34:51 CST 2021: [DEBUG] rats_tls_negotiate()@L15: handle 0x1c9e910, fd 4
Fri Dec 31 04:34:51 CST 2021: [DEBUG] openssl_tls_negotiate()@L110: ctx 0x1c9ea70, fd 4
Fri Dec 31 04:34:51 CST 2021: [DEBUG] openssl_internal_negotiate()@L92: success to negotiate
Fri Dec 31 04:34:51 CST 2021: [DEBUG] rats_tls_server_startup()@L211: Client connected successfully
Fri Dec 31 04:34:51 CST 2021: [DEBUG] rats_tls_receive()@L16: handle 0x1c9e910, buf 0x7ffd375915f0, buf_size 0x7ffd37591730 (256-byte)
Fri Dec 31 04:34:51 CST 2021: [DEBUG] openssl_tls_receive()@L13: ctx 0x1c9ea70, buf 0x7ffd375915f0, buf_size 0x7ffd37591730
[INFO] Client: Hello and welcome to RATS-TLS!

Fri Dec 31 04:34:51 CST 2021: [DEBUG] rats_tls_transmit()@L16: handle 0x1c9e910, buf 0x7ffd375915f0, buf_size 0x7ffd37591730 (31-byte)
Fri Dec 31 04:34:51 CST 2021: [DEBUG] openssl_tls_transmit()@L13: ctx 0x1c9ea70, buf 0x7ffd375915f0, buf_size 0x7ffd37591730
[INFO] Waiting for a connection ...

**Comment by jiazhang0** [comment]
Resolved by https://github.com/alibaba/inclavare-containers/pull/1539
