### ISSUE TITLE
ASOC: Enclave Network Gateway: 基于TEE/Enclave实现端到端数据网关

### ISSUE THREAD

**Issue by liangzhou121** [alibaba/inclavare-containers#1566]
# 项目名称
Enclave Network Gateway：基于TEE/Enclave实现端到端数据网关

# 难度
进阶

# 项目描述
基于RATS-TLS实现对应用无感知的端到端可信数据隧道，确保通过网络传输数据TLS通道的信任根来自TEE/Enclave而不是传统CA（比如TLS证书）。利用tap/tun设备的特点，基于[RATS-TLS](https://github.com/inclavare-containers/rats-tls)建立通信App无感知的安全数据隧道。

<img width="1065" alt="屏幕快照 2022-06-22 下午10 46 08" src="https://user-images.githubusercontent.com/10241344/175058974-405e7ecc-dc23-4558-bb55-9e35b92158cb.png">

# 项目产出要求

基于RATS-TLS实现Network Gateway的技术原型。

# 技术要求

- 熟练掌握C编程语言。
- 有一定网络编程知识和对tap/tun虚拟网络设备的工作原理了解。
- 有一定的HW-TEE或者机密计算方面的知识和开发经验。

# 导师姓名和联系方式

- 导师姓名：乾越
- 联系方式：钉钉：aluhazard    邮箱：qianyue.zj@alibaba-inc.com

# 参考信息

- [SGX SDK入门教程](https://www.intel.cn/content/www/cn/zh/developer/articles/training/introducing-the-intel-software-guard-extensions-tutorial-series.html)
- [Occlum项目](https://github.com/occlum/occlum)
- [rats-tls项目](https://github.com/inclavare-containers/rats-tls/)

**Comment by jiazhang0** [comment]
Completed. See https://github.com/inclavare-containers/enclave-network-gateway for details.
