### ISSUE TITLE
Could you provide a example

### ISSUE THREAD

**Issue by walter211** [alibaba/inclavare-containers#2]
such as running a python code

**Comment by jiazhang0** [comment]
@walter211 Currently python support is still unavailable, which depends on whether enclave runtime, such as occlum or graphene, can provide the support. As far as I know, graphene can support python. Additionally, launching graphene with rune is WIP.

**Comment by jiazhang0** [comment]
@walter211 Occlum also supports python recently. See https://github.com/occlum/occlum/tree/master/demos/python for details.
