### ISSUE TITLE
Enable DCAP driver for SGX 1 machine

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#203]
DCAP driver is available at https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/driver/linux.

We need to backport the patch https://github.com/alibaba/inclavare-containers/blob/master/patch/no-sgx-flc/0001-sgx-Support-SGX1-machine-even-without-FLC-support.patch to DCAP driver and see what happens.

If works, send the patch to DCAP repo for review.

**Comment by hustliyilin** [comment]
This PR #210 and this commit [0785e93](https://github.com/alibaba/inclavare-containers/commit/0785e935ccca63d8f52762ca2681ad3bc9d644ec) resolve this issue.
