### ISSUE TITLE
sgx-tools: support quote generation and verification (based on QVL)

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#205]
Depends on #620 

Provide DCAP RA and associated sub-functions.

**Comment by hustliyilin** [comment]
gen-qe-target-info and gen-quote is ready and merged. As for get-token and verification will be added in the next release.

**Comment by hustliyilin** [comment]
verification-related commands will be added by @zhiminghufighting

**Comment by hustliyilin** [comment]
Fixed by @hustliyilin in #632
