### ISSUE TITLE
Avoid pass EPM directories specified in config.json in rune

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#256]
Essentially, EPM communications are based on an opening unix socket fd. Creating a inter-process communication cross container boundary has already formed a formal flow to work in rune design. So it is not necessary to use the legacy way to pass EPM directories specified in config.json.

**Comment by YangLiang3** [comment]
If we can not use agentpipe as an exmple in epm. Because epm and rune are independent, they are not parent and child process. Pass Fd by env variables is not to make sensor. So I can keep one directory in config.json.  The direcotry can be used to dial by grpc communicating.
