### ISSUE TITLE
Many documents for Architecture and design details needed！

### ISSUE THREAD

**Issue by Apokleos** [alibaba/inclavare-containers#3]
Many documents for Architecture and design details needed！

**Comment by jiazhang0** [comment]
@Apokleos We are sorting out them and will be released soon.

**Comment by Apokleos** [comment]
> @Apokleos We are sorting out them and will be released soon.

Thx @jiazhang0, Waiting for them！！！

**Comment by jiazhang0** [comment]
@Apokleos Sorry for late reply. You could refer to this slide for the details about rune's design. https://inclavare-containers.io/blog/oci-runtime-rune/
