### ISSUE TITLE
EAA：Define the EAA protocol

### ISSUE THREAD

**Issue by liying-000** [alibaba/inclavare-containers#318]
The following 2 functions must be implemented:

- Attestation
- Secret Provisioning

**Comment by liangzhou121** [comment]
1. Define communication protocol between AA and sheltered. The protocol should be a JSON format.
2. Define communication protocol between sheltered and verdictd, the protocol should based on GPRC.

**Comment by jiazhang0** [comment]
This is already done in current EAA.
