### ISSUE TITLE
Is it possible to run applications without modification in inclavare-containers?

### ISSUE THREAD

**Issue by qiyuangong** [alibaba/inclavare-containers#4]
Looking for SGX LibOS docker solutions. 

Is it possible to run applications without modification in inclavare-containers?

**Comment by jiazhang0** [comment]
@qiyuangong Graphene-SGX libos is adapting to inclavare-containers, which will be available in next release of inclavare-containers.

**Comment by qiyuangong** [comment]
OK. Thanks :)
