### ISSUE TITLE
Inspect the behavior of rune operated by docker

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#403]
How the config.json and rune cmdline operated is not explicitly known yet. This is a potential problem of rune.

**Comment by haosanzi** [comment]
The set of commands and parameters executed by the container entry point is the `process.args` parameter in the `config.json` file.
The results of the following two cases are consistent, which can be:
• The result of cascading Path and Args in `docker inspect` command
• The result of cascading `Config.Entrypoint` and `Config.Cmd` in the `docker inspect` command
