### ISSUE TITLE
Discuss whether dropping the use of centos 8.1 docker image made for Inclavare Containers project

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#407]

**Comment by jiazhang0** [comment]
It looks like we need to find a substitute. However, Inclavare Containers stills depends on intel sgx sdk, and thus we follow up the schedule of Intel sgx sdk for the support lifecycleo centos 8.1.

**Comment by hustliyilin** [comment]
`intel-sgx` github released `sgxsdk/psw` 2.12 and changed `centos 8.1` to `centos 8.2`. And `01.org` doesn't support `centos 8.1` any more. However, `01.org` and `intel-sgx` both support `ubuntu 16.04`, `18.04`, and `20.04`.

**Comment by jiazhang0** [comment]
> `intel-sgx` github released `sgxsdk/psw` 2.12 and changed `centos 8.1` to `centos 8.2`. And `01.org` doesn't support `centos 8.1` any more. However, `01.org` and `intel-sgx` both support `ubuntu 16.04`, `18.04`, and `20.04`.

Ideally, we should follow up centos 8.2 if we decide to still follow up centos. However, something is not ideal.

- No build host. GitHub build machine doesn't provide centos 8.2.
- No requirement. Occlum depends on sgxsdk/psw but it doesn't require 2.12 in the short term.
- No motivation. We don't want to build sgxsdk/psw by ourself as a sacrifice.

So we still stick at 2.11.

**Comment by hustliyilin** [comment]
Already update centos 8.2 in #712
