### ISSUE TITLE
CI/CD: If an error occurs in the preceding step, the subsequent execution should stop

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#486]
Assuming 1 and 2 are pre-preparation steps, 3 and 4 are test steps:
Need to achieve:
3 and 4 are independent of each other, the error of 3 will not cause the problem of 4
3 and 4 depend on 1 and 2, and 1 and 2 are independent. Any problem with 1 or 2 should prevent 3 and 4 from running.

**Comment by jiazhang0** [comment]
Duplicated to https://github.com/alibaba/inclavare-containers/issues/846
