### ISSUE TITLE
Is runE going to be upstream to OCI runtime spec ?

### ISSUE THREAD

**Issue by yang8621** [alibaba/inclavare-containers#5]
https://github.com/opencontainers/runtime-spec/blob/master/implementations.md

**Comment by jiazhang0** [comment]
@yang8621 Yes we have this plan. In the best situation it would be merged into runc :)

**Comment by yang8621** [comment]
thanks

**Comment by jiazhang0** [comment]
> thanks

Already written into https://github.com/opencontainers/runtime-spec/blob/master/implementations.md

**Comment by yang8621** [comment]
Thank you for your information. This is a great promotion for SGX ecosystem. Congratulations!
