### ISSUE TITLE
CI/CD: sgx2 workflows can hardly server on weekends however sgx1 could.

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#713]

**Comment by hustliyilin** [comment]
Almost all failed workflows are sgx2 workflows, and the reason is that it can't `set up jobs` in all sgx2 workflows.

![image](https://user-images.githubusercontent.com/6824093/111893442-a58c3700-8a3d-11eb-9ea9-317ff3cc2442.png)

![image](https://user-images.githubusercontent.com/6824093/111893446-aae98180-8a3d-11eb-912d-6c2c5602dab2.png)

![image](https://user-images.githubusercontent.com/6824093/111893449-b046cc00-8a3d-11eb-9063-516d681229fe.png)

**Comment by haosanzi** [comment]
SGX2 machine is in Shenzhen, while SGX1 is in shanghai. I used to find that the network of the shanghai machine is better than Shenzhen.
Anyway, I will find a way to solve the network problem of GitHub checkout action with proxy.
