### ISSUE TITLE
CI/CD: alinuxs2 sdk and psw can not work in SGX1 machine

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#728]
Install the binaries  in `https://mirrors.openanolis.org/inclavare-containers/alinux2/`
Sample code in SGX2 is work, however, in SGX1 is failed.

failed infomation is:
```
# /opt/intel/sgx-aesm-service/aesm/aesm_service --no-daemon
The path of system bundle: System Bundle
ecdsa_quote_service_bundle_name:2.0.0
epid_quote_service_bundle_name:2.0.0
le_launch_service_bundle_name:2.0.0
linux_network_service_bundle_name:2.0.0
pce_service_bundle_name:2.0.0
quote_ex_service_bundle_name:2.0.0
system_bundle:4.0.0
Segmentation fault (core dumped)
```

**Comment by hustliyilin** [comment]
`https://mirrors.openanolis.org/inclavare-containers/alinux2/` need `protobuf 3.5` in the `alinux2`. So please make sure you install the corresponding protobuf version in the `alinux2`. Just following

```shell
yum install -y  alinux-release-experimentals
yum install -y protobuf protobuf-devel protobuf-c-devel
```
