### ISSUE TITLE
CI/CD: enclave-tls la attestation failed on SGX1 machine

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#827]
![image](https://user-images.githubusercontent.com/26923638/115822157-a4806800-a436-11eb-92fd-d59d1983b29b.png)

Enclave-tls ci/cd will only test `nullquote` on SGX1 machine to workaround this problem,

**Comment by jiazhang0** [comment]
@liying-000 Please track this issue.

**Comment by jiazhang0** [comment]
This issue is resolved by https://github.com/alibaba/inclavare-containers/pull/853
