### ISSUE TITLE
CI/CD: build and install shelter rpm failed

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#828]
![image](https://user-images.githubusercontent.com/26923638/115822419-1b1d6580-a437-11eb-921f-4bca3fd9eecf.png)

In this [test](https://github.com/alibaba/inclavare-containers/runs/2416428310?check_suite_focus=true), the process of build shelter rpm is failed due to a network problem.

Config git proxy can solve this problem, the detailed information refer to this [link](https://github.com/alibaba/inclavare-containers/blob/master/.github/workflows/commit_shelter.yml#L28)

**Comment by jiazhang0** [comment]
@liying-000 Please track this issue.

**Comment by haosanzi** [comment]
![image](https://user-images.githubusercontent.com/26923638/115981300-4209a200-a5c5-11eb-8020-e4b21bceae53.png)
If solves the network problem, then `rpm -ivh shelter.rpm` still has failed dependencies problem.
