### ISSUE TITLE
failed to build skeleton docker image

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#836]
```
make[1]: Leaving directory `/root/inclavare-containers-0.6.0/rune/libenclave/internal/runtime/pal/kvmtool'
143
cc sgx_call.o liberpal-skeleton-v1.o liberpal-skeleton.o sgxutils.o aesm.o aesm.pb-c.o ../kvmtool/libvmm.a -fPIC -shared -Wl,-Bsymbolic,-rpath=/opt/enclave-tls/lib,-enable-new-dtags -Wl,-start-group -lprotobuf-c -lutil -lbfd -lpthread -Wl,-end-group -o liberpal-skeleton-v1.so
144
cc sgx_call.o liberpal-skeleton-v2.o liberpal-skeleton.o sgxutils.o aesm.o aesm.pb-c.o ../kvmtool/libvmm.a -fPIC -shared -Wl,-Bsymbolic,-rpath=/opt/enclave-tls/lib,-enable-new-dtags -Wl,-start-group -lprotobuf-c -lutil -lbfd -lpthread -Wl,-end-group -o liberpal-skeleton-v2.so
145
cc sgx_call.o liberpal-skeleton-v3.o liberpal-skeleton.o sgxutils.o aesm.o aesm.pb-c.o ../kvmtool/libvmm.a -fPIC -shared -Wl,-Bsymbolic,-rpath=/opt/enclave-tls/lib,-enable-new-dtags -Wl,-start-group -lprotobuf-c -lutil -lbfd -lpthread -Wl,-end-group -o liberpal-skeleton-v3.so
146
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
147
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
148
Error: Process completed with exit code 1.
```

https://github.com/alibaba/inclavare-containers/pull/834/checks?check_run_id=2424578527
https://github.com/alibaba/inclavare-containers/pull/834/checks?check_run_id=2424578542
https://github.com/alibaba/inclavare-containers/pull/834/checks?check_run_id=2424578558
https://github.com/alibaba/inclavare-containers/pull/839/checks?check_run_id=2427171131
https://github.com/alibaba/inclavare-containers/pull/839/checks?check_run_id=2427171088

**Comment by jiazhang0** [comment]
@liying-000 Please track this issue.

**Comment by hustliyilin** [comment]
It can be found that in the newest  `inclavarecontainers/dev:0.6.0-alinux2` docker image dockerd can't start successfully. Just following these steps to reproduce this problem @haosanzi @jiazhang0 

- steps 1: ` docker run -it --rm --privileged inclavarecontainers/dev:0.6.0-alinux2`
- steps 2: `dockerd -b docker0 &`
