### ISSUE TITLE
failed to create occlum docker image

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#837]
```
Unable to find image 'rune-test:alinux2' locally
12
docker: Error response from daemon: pull access denied for rune-test, repository does not exist or may require 'docker login'.
13
See 'docker run --help'.
14
Error: Process completed with exit code 125.
```

https://github.com/alibaba/inclavare-containers/pull/834/checks?check_run_id=2424578518
https://github.com/alibaba/inclavare-containers/pull/839/checks?check_run_id=2427171119
https://github.com/alibaba/inclavare-containers/pull/839/checks?check_run_id=2427171095

**Comment by jiazhang0** [comment]
@liying-000 Please track this issue.

**Comment by hustliyilin** [comment]
There are five types CI/CD in inclavare containers.

- nightly: run in the host environment.
- compile-check:  run in the github machine.
- inclavare containers docker images build: run in the github machine.
- occlum normal commit CI/CD: run in the occlum docker images.
- other commit CI/CDs: build in the inclavare-dev docker images and run in the inclavare-test docker images.

This problem should run in the occlum docker images. However, the `runner 21` host environment doesn't have the corresponding occlum docker images. So please fix it manually @haosanzi. FYI @jiazhang0

**Comment by haosanzi** [comment]
`rune-test:alinux2` does not exist in the new vsgx cicd machine. I have manually pulled this test image.
