### ISSUE TITLE
failed to generate evidence

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#838]
```
Error:  failed to generate evidence 0xf
10
failed to negotiate 0x30000000
```

https://github.com/alibaba/inclavare-containers/pull/834/checks?check_run_id=2424993312

**Comment by jiazhang0** [comment]
@liying-000 Please track this issue.

**Comment by YangLiang3** [comment]
current implementation for sgx local attestation is based on ecdsa which is leveraging QE to verify Local report indirectly.
So ECDSA requires machine with SGX2 not SGX1. 
So if running LA on SGX1 in testing will fail.
