### ISSUE TITLE
Github actions checkout v2 failing 

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#851]
Some discussion is shown in [this page ](https://github.com/actions/checkout/issues/256) and [link](https://github.com/actions/checkout/issues/254)

**Comment by haosanzi** [comment]
![image](https://user-images.githubusercontent.com/26923638/116052646-67251000-a6ac-11eb-930b-491d453915ad.png)

**Comment by jiazhang0** [comment]
Actually adding a retry attribute is absolutely correct.

**Comment by jiazhang0** [comment]
All runner is enabled with proxy so this problem has been resolved.
