### ISSUE TITLE
non-sgx  enclave-tls-client + sgx enclave-tls-server error mesages

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#934]
- server: sgx
![image](https://user-images.githubusercontent.com/6824093/117610734-d0208380-b194-11eb-902b-d4abbb5bd5ff.png)

- client: non-sgx

![image](https://user-images.githubusercontent.com/6824093/117615116-debe6900-b19b-11eb-8e08-cf707b94adca.png)

- mrenclave and mrsigner aren't printed

**Comment by jiazhang0** [comment]
@hustliyilin Why non-sgx platform runs with sgx instances?

**Comment by YangLiang3** [comment]
it seems that the error can't be avoided according to sgx-sdk's implementation.   In load_qve, it will judge that libsgx_urts lib is absence or not. If it has been there, then it will be create qve.

**Comment by jiazhang0** [comment]
@zhiminghufighting @YangLiang3 Please document well about this error in shelter and enclave-tls readme.
