### ISSUE TITLE
rats-tls: pass hash_len according to different algos while collecting evidence

### ISSUE THREAD

**Issue by Ruoyu-y** [alibaba/inclavare-containers#938]
Since the cert algo can be changed, the size of hash may change accordingly. Pass the hash_len param to define the size.

**Comment by jiazhang0** [comment]
In future, sha256 is not the only available hash algorithm parameter. All possible algorithm parameter will defined in global configuration file of rats-tls. See https://github.com/alibaba/inclavare-containers/issues/1261.
