### ISSUE TITLE
enclave-tls/wolfcrypt-sgx: fix build warnnings

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#943]
In file included from ../crypto_wrappers/wolfcrypt-sgx/ecalls.c:14:
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c: In function 'wolfcrypt_gen_cert':
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c:43:32: warning: conversion to 'int' from 'uint32_t' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
   43 |   crt.iasAttestationReportSz = epid->ias_report_len;
      |                                ^~~~
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c:47:24: warning: conversion to 'int' from 'uint32_t' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
   47 |   crt.iasSigCACertSz = epid->ias_sign_ca_cert_len;
      |                        ^~~~
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c:51:22: warning: conversion to 'int' from 'uint32_t' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
   51 |   crt.iasSigCertSz = epid->ias_sign_cert_len;
      |                      ^~~~
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c:55:18: warning: conversion to 'int' from 'uint32_t' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
   55 |   crt.iasSigSz = epid->ias_report_signature_len;
      |                  ^~~~
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c:60:17: warning: conversion to 'int' from 'uint32_t' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
   60 |   crt.quoteSz = ecdsa->quote_len;
      |                 ^~~~~
../crypto_wrappers/wolfcrypt-sgx/../wolfcrypt/gen_cert.c:65:20: warning: conversion to 'int' from 'uint32_t' {aka 'unsigned int'} may change the sign of the result [-Wsign-conversion]
   65 |   crt.lareportSz = la->report_len;
      |                    ^~
CC   <=  ../crypto_wrappers/wolfcrypt-sgx/ecalls.c

**Comment by jiazhang0** [comment]
> @jiazhang0 quick question, i saw there're two patches available in the repo on wolfssl/wolfcrypt/asn_public.h adding extra params in the Cert struct. Which is /ra-tls/patch/wolfssl.patch and /enclave-tls/src/external/wolfssl/patch/wolfssl.patch
> Which one are you using in the build environment?

The latter. ra-tls code is depreciated already.

**Comment by Ruoyu-y** [comment]
> > @jiazhang0 quick question, i saw there're two patches available in the repo on wolfssl/wolfcrypt/asn_public.h adding extra params in the Cert struct. Which is /ra-tls/patch/wolfssl.patch and /enclave-tls/src/external/wolfssl/patch/wolfssl.patch
> > Which one are you using in the build environment?
> 
> The latter. ra-tls code is depreciated already.

Then i am a bit confused. As according to the latter patch, the type of iasAttestationReportSz(also others) is already changed to 'unsigned int'. Why this conversion happened?

**Comment by jiazhang0** [comment]
@Ruoyu-y Sorry I forgot to clean up the local cache. So this problem is gone.
