### ISSUE TITLE
shelter:  fix the bug of output successful attestation even the attestation is failed

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#945]
![image](https://user-images.githubusercontent.com/26923638/117671951-ec93de80-b1db-11eb-81f2-acbbfe850ff2.png)

**Comment by zhiminghufighting** [comment]
![image](https://user-images.githubusercontent.com/33820274/117947624-f4ba5e00-b342-11eb-9eff-a06ea63a108e.png)
This version is built and run based on cimmit id:e9f525f0a4247a1699c132b0cbf8ad5f869eb640 on 5/12/2021.
When RA failed, it will report failed result log.

**Comment by zhiminghufighting** [comment]
Actually, it is fixed in the commit: 7c96c6766ad071a2f6da6dc31356cd582aeaedbd with a unified feature change. So i didn't separate the feature into two commits.

**Comment by zhiminghufighting** [comment]
Suggest to close it. 
Fixes commit: https://github.com/alibaba/inclavare-containers/commit/7c96c6766ad071a2f6da6dc31356cd582aeaedbd
