### ISSUE TITLE
CI/CD: run shelter for null quote error(ERROR: failed to cleanup)

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#986]
Error Link: https://github.com/alibaba/inclavare-containers/pull/982/checks?check_run_id=2572822048

![image](https://user-images.githubusercontent.com/6824093/118084556-82ee1d00-b3f3-11eb-82d9-dd7434d8841e.png)

**Comment by zhiminghufighting** [comment]
Local verify such case and it can't be reproduced. Suggest to keep it as monitor and push it into 0.6.2.
![image](https://user-images.githubusercontent.com/33820274/118596858-83652a00-b7de-11eb-8f76-d592468b39ad.png)

**Comment by zhiminghufighting** [comment]
![image](https://user-images.githubusercontent.com/33820274/118596963-a5f74300-b7de-11eb-8b14-b89382ec19bc.png)

**Comment by zhiminghufighting** [comment]
No cleanup failed issue base on new enclave-tls lib at master branch commit id:51bf151b6edfd004362024438bb1287ad7611a94

**Comment by zhiminghufighting** [comment]
@hustliyilin, if it can't be reproduced in your side, please keep it as open and i will monitor it.

**Comment by haosanzi** [comment]
This problem has not been reproduced recently.
