### ISSUE TITLE
rune：shouldn't write --devel sgx and dcap rpm in the build require and readme

### ISSUE THREAD

**Issue by hustliyilin** [alibaba/inclavare-containers#991]

**Comment by hustliyilin** [comment]
Also, rune shouldn't write --dev sgx and dcap dev in the build require and readme

**Comment by jiazhang0** [comment]
rune requires libsgx-dcap-quote-verify-devel because attestation package uses cgo to call qvl and thus needs the header files provided by libsgx-dcap-quote-verify-devel.
